import { ArrowUpRight, ArrowDown, MapPin, ScanLine, RadioTower, Network } from 'lucide-react';
const projects = [
 {n:'01', type:'REMOTE SENSING · MACHINE LEARNING', title:'Reading the earth. Predicting the crop.', name:'Satellite-Based Crop Classification & Prediction', text:'A multi-temporal workflow combining Sentinel-1 SAR and Sentinel-2 multispectral imagery to distinguish crop categories across growth stages.', detail:'Analyzes satellite bands, vegetation indices, and temporal changes in spectral and SAR characteristics to support crop identification and prediction.', tags:['Python','Google Earth Engine','Sentinel-1 & 2'], Icon:ScanLine},
 {n:'02', type:'COMPUTER VISION · INFRASTRUCTURE', title:'A closer look at critical infrastructure.', name:'Transmission Tower Detection & Thermal Distress Monitoring', text:'An infrastructure monitoring workflow for transmission tower detection and condition analysis using RGB, thermal, and 3D information.', detail:'Focuses on thermal anomalies, tower distress, and nearby vegetation growth to support monitoring and maintenance analysis.', tags:['RGB & thermal analysis','3D data','Vegetation monitoring'], Icon:RadioTower},
 {n:'03', type:'MATHEMATICAL OPTIMIZATION', title:'The right location. A better network.', name:'P-Median Facility Location Optimization', text:'A mixed integer programming model for a nine-city network, selecting three warehouses and assigning every customer to exactly one facility.', detail:'Implemented in IBM CPLEX Optimization Studio with OPL, using demand data, inter-city distances, and binary decision variables for facility opening and customer assignments.', tags:['IBM CPLEX','OPL','Mixed Integer Programming'], Icon:Network},
];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<header id="top"><a className="brand" href="#top">km<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={16}/></a></nav></header>
<main id="main">
<section className="hero"><div className="eyebrow"><span className="dot"/> AI / ML DEVELOPER · KOLKATA, INDIA</div><h1>Turning data into<br/><span>real-world insight.</span></h1><div className="hero-bottom"><div><p>I’m Krishnendu Majumder. I work at the intersection of machine learning, satellite intelligence, and practical problem-solving.</p><a className="button" href="#work">Explore my work <ArrowDown size={18}/></a></div><div className="hero-note"><span>FOCUS AREAS</span><p>Earth observation<br/>Predictive modeling<br/>Optimization</p></div></div><div className="hero-footer"><span>KRISHNENDU MAJUMDER</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section id="work" className="section"><div className="section-heading"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Ideas, applied.</h2></div><p>From agricultural fields to infrastructure networks.</p></div><div className="projects">{projects.map(({n,type,title,name,text,detail,tags,Icon})=><article key={n} className="project"><div className="project-top"><span className="project-number">{n}</span><Icon size={40} strokeWidth={1}/></div><div className="eyebrow">{type}</div><h3>{title}</h3><h4>{name}</h4><p>{text}</p><details><summary>Project approach <span>+</span></summary><p>{detail}</p></details><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
<section id="about" className="section about"><div><div className="eyebrow">02 / ABOUT ME</div><h2>Curious by nature.<br/>Driven to build.</h2></div><div><p className="large-copy">A computer science background. A hands-on interest in what data can do.</p><p>I’m an enthusiastic, quick-learning developer with a foundation in Python, Java, C, and SQL. My interests span artificial intelligence, data science, and web development.</p><p>Through my work in agricultural AI and satellite analysis, I’ve explored how technical ideas can support crop monitoring and precision farming. I’m eager to keep learning and contribute to meaningful projects.</p><div className="skill-group"><h3>My toolkit</h3><div className="tags">{['Python','SQL','Java','C','Data Science','Predictive Modeling','Remote Sensing','Google Earth Engine','KML / Geospatial Data','IBM CPLEX / OPL'].map(t=><span key={t}>{t}</span>)}</div></div><div className="languages">LANGUAGES <span>English · Hindi · Bengali</span></div></div></section>
<section id="experience" className="section"><div className="section-heading"><div><div className="eyebrow">03 / EXPERIENCE & LEARNING</div><h2>Building a foundation.</h2></div></div><div className="timeline"><article><div className="time">6-MONTH PAID INTERNSHIP</div><div><h3>AI/ML Developer Intern</h3><h4>PlanetEye Farm-AI Limited</h4><p>Contributed to AI- and satellite-based agricultural solutions, including remote sensing, crop monitoring, data analysis, and machine-learning workflows.</p><ul><li>Worked with Sentinel-1 SAR and Sentinel-2 multispectral imagery.</li><li>Supported multi-temporal crop classification using satellite bands and vegetation indices.</li><li>Worked with KML field data and Google Earth Engine extraction workflows.</li></ul></div></article><article><div className="time">JUL — AUG 2024</div><div><h3>Full Stack Development in Python</h3><h4>National Institute for Industrial Training, Kolkata</h4><p>Developed a social media platform concept covering profiles, connections, posts, messaging, and moderation. Training included Python backend frameworks, databases, REST APIs, authentication, WebSockets, and modern frontend technologies.</p></div></article></div><div className="education"><h3>Education</h3><div><article><span>2022 — 2025</span><h4>B.Tech · Computer Science Engineering</h4><p>RCC Institute of Information Technology, Kolkata</p></article><article><span>2019 — 2022</span><h4>Computer Science and Technology</h4><p>Elitte Institute of Engineering & Management, Kolkata</p></article><article><span>2019 / 2017</span><h4>Higher Secondary / Secondary Education</h4><p>Hare School, Kolkata</p></article></div></div></section>
<section id="contact" className="contact"><div className="eyebrow">04 / GET IN TOUCH</div><h2>Have something<br/>in mind<span>?</span></h2><p>Let’s connect about AI, data science, and opportunities to build something useful.</p><a className="email" href="mailto:krishnendumajumder32@gmail.com">krishnendumajumder32@gmail.com <ArrowUpRight/></a><div className="contact-bottom"><div><a href="tel:+919038709232">+91 90387 09232</a><a href="tel:+919038959441">+91 90389 59441</a></div><span><MapPin size={16}/> Kolkata, India</span></div></section>
</main><footer><a className="brand" href="#top">km<span>.</span></a><span>© {new Date().getFullYear()} Krishnendu Majumder</span><a href="#top">Back to top ↑</a></footer></>}

